### ISSUE TITLE
reset function is not working!

### ISSUE THREAD

**Issue by FaranNavazi** [FaranNavazi/unit4game#6]
it is as simple as the title! :)

**Comment by antoniojgage** [comment]
@FaranNavazi send me where its hosted

**Comment by antoniojgage** [comment]
function reset() {
      var randomNumber = Math.floor(Math.random()* 50 + 50);
      $("#randomNumber").text(randomNumber);
      var userTotal = 0;
      $("#userTotal").text(userTotal);
  }

This is a scoping issue. You're creating a new userTotal inside reset.

**Comment by FaranNavazi** [comment]
Thanks to @antoniojgage and Alec(TU) this issue has been resolved. Just remember scoping is very important and one mistake could turn your whole day to ... we all know what! Thank you guys again.
